### ISSUE TITLE
Progress query

### ISSUE THREAD

**Issue by yasoob** [FlySolutions/akamai-bypass-1.6#1]
Hi! I checked out this repo and some of your other repos during my research on how to bypass Akamai bot detection. Any idea when you will be finished with this script? Also Akamai bot manager also sets the `bm_sz` cookie. Any idea how to get that?

And just out of curiosity, how did you reverse engineer this? By going through a JS lib used by some website?

Thanks!

**Comment by yasoob** [comment]
I guess the answer for the reversing part is that you used the mobile SDK for Akamai to reverse this.

**Comment by FlySolutions** [comment]
@yasoob hi sorry for late reply. this is not the SDK, this is the web version. You can deobfuscate the akamai script via Array mode on de4js. And also i will not be publishing anymore of this script as if i do akamai will simply patch it very very quick

**Comment by FlySolutions** [comment]
the bm_sz is a response cookie you get when posting the sensor

**Comment by yasoob** [comment]
That answers my question. Thanks :)
